import type {NextPage} from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import fetch from "node-fetch";
import {useEffect, useState} from "react";

type Product = {
  id: number;
  title: string;
}

const Home: NextPage = () => {
  const [products, setProducts] = useState<Product[]>([])
  const [isAuthed, setIsAuthed] = useState(false)
  const [shop, setShop] = useState('')

  useEffect(() => {
    (async () => {
      const data = await fetch('/api/products')
      if (data.status !== 200) {
        return;
      }
      setIsAuthed(true);
      setProducts(await data.json());
    })()
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <main className={styles.main}>
        {isAuthed ?
          (
            <>
              <p>Shopifyで商品を登録すると表示されます</p>
              <ul>
                {products.map(item => <li key={item.id}>
                  <p>{item.title}</p>
                  <a href={`/products/${item.id}`}>この商品の撮影依頼をする</a>
                </li>)}
              </ul>
            </>
          ) : (
            <>
              <label>Shopifyのショップ名xxxxx.myshopify.comのxxxxxの部分を入力してください</label>
              <input  onChange={event => {
                setShop(event.target.value)
              }}/>
              <a href={`/api/login?shop=${shop}.myshopify.com`}>ログイン</a>
            </>
          )
        }
      </main>
    </div>
  )
}

export default Home
